"""empty message

Revision ID: 089a437774bb
Revises: 475182775b2e
Create Date: 2023-06-20 18:53:29.675761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '089a437774bb'
down_revision = '475182775b2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.drop_column('time')

    # ### end Alembic commands ###
