"""empty message

Revision ID: 3532b00bc984
Revises: ac4f1a6996fb
Create Date: 2023-06-17 13:43:39.863337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3532b00bc984'
down_revision = 'ac4f1a6996fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('passenger')
    op.drop_table('payment_passenger')
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_column('date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.VARCHAR(length=255), nullable=False))

    op.create_table('payment_passenger',
    sa.Column('payment_id', sa.INTEGER(), nullable=True),
    sa.Column('passenger_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['passenger_id'], ['passenger.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.id'], )
    )
    op.create_table('passenger',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('email', sa.VARCHAR(length=70), nullable=False),
    sa.Column('password', sa.VARCHAR(length=40), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=False),
    sa.Column('address', sa.VARCHAR(length=200), nullable=False),
    sa.Column('loc', sa.VARCHAR(length=40), nullable=False),
    sa.Column('status', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
