"""empty message

Revision ID: 475182775b2e
Revises: 5ee971d3c44f
Create Date: 2023-06-20 16:58:11.235150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '475182775b2e'
down_revision = '5ee971d3c44f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.DateTime(),
               nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('lastName', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('lastName')
        batch_op.drop_column('name')

    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
