"""empty message

Revision ID: 7cf893d396a5
Revises: fca208ec92c1
Create Date: 2023-07-20 20:14:07.286510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cf893d396a5'
down_revision = 'fca208ec92c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('no')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('no', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
