"""empty message

Revision ID: 80d4385c9705
Revises: 05df52db23ff
Create Date: 2023-07-16 14:23:56.359866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80d4385c9705'
down_revision = '05df52db23ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('class_ctg',
               existing_type=sa.FLOAT(),
               type_=sa.Boolean(),
               existing_nullable=False)

    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_role_name'), ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_role_name'), type_='unique')

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('class_ctg',
               existing_type=sa.Boolean(),
               type_=sa.FLOAT(),
               existing_nullable=False)

    # ### end Alembic commands ###
