"""empty message

Revision ID: e84ec7334397
Revises: 089a437774bb
Create Date: 2023-06-20 20:34:52.226735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e84ec7334397'
down_revision = '089a437774bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('times', sa.DateTime(), nullable=True))
        batch_op.drop_column('time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', sa.DATETIME(), nullable=True))
        batch_op.drop_column('times')

    # ### end Alembic commands ###
